<?xml version="1.0"?>
<package format="3">
<name>synchronized_throttle</name>
<version>1.0.0</version>
<description>Container for throttling image stream</description>

  <!-- Required -->
  <maintainer email="no@ltu.edu">TODO</maintainer>
  <license>no one cares</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>image_transport</depend>
  <depend>message_filters</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
